"""MoviesModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import MoviesModel as OptionalModel
from .strict_models import MoviesModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Accent,
        Artwork,
        Artwork1,
        Artwork2,
        Artwork3,
        Artwork4,
        Availability,
        Browse,
        Browse1,
        Bundle,
        Bundle1,
        Bundle2,
        Component,
        Credit,
        DetailHorizontalHero,
        DetailHorizontalHero1,
        DetailHorizontalHero2,
        DetailHorizontalHero3,
        DetailVerticalHero,
        DetailVerticalHero1,
        DetailVerticalHero2,
        DetailVerticalHero3,
        Details,
        Entity,
        Entity1,
        ExternalIdentifier,
        Focus,
        Item,
        Item1,
        MetricsInfo,
        MetricsInfo1,
        MetricsInfo2,
        MetricsInfo3,
        MetricsInfo4,
        MetricsInfo5,
        MoviesModel,
        Pagination,
        Personalization,
        Personalization1,
        ProgramTile,
        ProgramTile1,
        ProgramTile2,
        ProgramTile3,
        ProgramVerticalTile,
        ProgramVerticalTile1,
        ProgramVerticalTile2,
        ProgramVerticalTile3,
        Rating,
        Rights,
        TitleTreatmentHorizontal,
        TitleTreatmentHorizontal1,
        TitleTreatmentHorizontal2,
        TitleTreatmentHorizontal3,
        Trailer,
        UserState,
        VideoHorizontalHero,
        VideoHorizontalHero1,
        VideoHorizontalHero2,
        VideoHorizontalHero3,
        VideoHorizontalHero4,
        VodItems,
    )
else:
    from .optional_models import (
        Accent,
        Artwork,
        Artwork1,
        Artwork2,
        Artwork3,
        Artwork4,
        Availability,
        Browse,
        Browse1,
        Bundle,
        Bundle1,
        Bundle2,
        Component,
        Credit,
        DetailHorizontalHero,
        DetailHorizontalHero1,
        DetailHorizontalHero2,
        DetailHorizontalHero3,
        DetailVerticalHero,
        DetailVerticalHero1,
        DetailVerticalHero2,
        DetailVerticalHero3,
        Details,
        Entity,
        Entity1,
        ExternalIdentifier,
        Focus,
        Item,
        Item1,
        MetricsInfo,
        MetricsInfo1,
        MetricsInfo2,
        MetricsInfo3,
        MetricsInfo4,
        MetricsInfo5,
        MoviesModel,
        Pagination,
        Personalization,
        Personalization1,
        ProgramTile,
        ProgramTile1,
        ProgramTile2,
        ProgramTile3,
        ProgramVerticalTile,
        ProgramVerticalTile1,
        ProgramVerticalTile2,
        ProgramVerticalTile3,
        Rating,
        Rights,
        TitleTreatmentHorizontal,
        TitleTreatmentHorizontal1,
        TitleTreatmentHorizontal2,
        TitleTreatmentHorizontal3,
        Trailer,
        UserState,
        VideoHorizontalHero,
        VideoHorizontalHero1,
        VideoHorizontalHero2,
        VideoHorizontalHero3,
        VideoHorizontalHero4,
        VodItems,
    )

__all__ = [
    "Accent",
    "Artwork",
    "Artwork1",
    "Artwork2",
    "Artwork3",
    "Artwork4",
    "Availability",
    "Browse",
    "Browse1",
    "Bundle",
    "Bundle1",
    "Bundle2",
    "Component",
    "Credit",
    "DetailHorizontalHero",
    "DetailHorizontalHero1",
    "DetailHorizontalHero2",
    "DetailHorizontalHero3",
    "DetailVerticalHero",
    "DetailVerticalHero1",
    "DetailVerticalHero2",
    "DetailVerticalHero3",
    "Details",
    "Entity",
    "Entity1",
    "ExternalIdentifier",
    "Focus",
    "Item",
    "Item1",
    "MetricsInfo",
    "MetricsInfo1",
    "MetricsInfo2",
    "MetricsInfo3",
    "MetricsInfo4",
    "MetricsInfo5",
    "MoviesModel",
    "Pagination",
    "Personalization",
    "Personalization1",
    "ProgramTile",
    "ProgramTile1",
    "ProgramTile2",
    "ProgramTile3",
    "ProgramVerticalTile",
    "ProgramVerticalTile1",
    "ProgramVerticalTile2",
    "ProgramVerticalTile3",
    "Rating",
    "Rights",
    "TitleTreatmentHorizontal",
    "TitleTreatmentHorizontal1",
    "TitleTreatmentHorizontal2",
    "TitleTreatmentHorizontal3",
    "Trailer",
    "UserState",
    "VideoHorizontalHero",
    "VideoHorizontalHero1",
    "VideoHorizontalHero2",
    "VideoHorizontalHero3",
    "VideoHorizontalHero4",
    "VodItems",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> MoviesModel:
    """Read a downloaded file into MoviesModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
