"""EpisodeModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import EpisodeModel as OptionalModel
from .strict_models import EpisodeModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Accent,
        Artwork,
        Artwork1,
        Artwork2,
        Artwork3,
        Availability,
        BrandLogo,
        BrandLogoBottomRight,
        BrandLogoTopRight,
        BrandWatermark,
        BrandWatermarkBottomRight,
        BrandWatermarkTopRight,
        Browse,
        Browse1,
        Bundle,
        DetailHorizontalHero,
        DetailHorizontalHero1,
        DetailVerticalHero,
        DetailVerticalHero1,
        Details,
        Entity,
        Entity1,
        EpisodeModel,
        ExternalIdentifier,
        Focus,
        MetricsInfo,
        MetricsInfo1,
        MetricsInfo2,
        MetricsInfo3,
        NetworkTile,
        Personalization,
        PrimaryBranding,
        ProgramTile,
        ProgramTile1,
        ProgramVerticalTile,
        ProgramVerticalTile1,
        Rating,
        Rights,
        SeriesArtwork,
        SeriesArtwork1,
        TitleTreatmentHorizontal,
        TitleTreatmentHorizontal1,
        UserState,
        VideoHorizontalHero,
        VideoHorizontalHero1,
        VideoHorizontalHero2,
        VodItems,
    )
else:
    from .optional_models import (
        Accent,
        Artwork,
        Artwork1,
        Artwork2,
        Artwork3,
        Availability,
        BrandLogo,
        BrandLogoBottomRight,
        BrandLogoTopRight,
        BrandWatermark,
        BrandWatermarkBottomRight,
        BrandWatermarkTopRight,
        Browse,
        Browse1,
        Bundle,
        DetailHorizontalHero,
        DetailHorizontalHero1,
        DetailVerticalHero,
        DetailVerticalHero1,
        Details,
        Entity,
        Entity1,
        EpisodeModel,
        ExternalIdentifier,
        Focus,
        MetricsInfo,
        MetricsInfo1,
        MetricsInfo2,
        MetricsInfo3,
        NetworkTile,
        Personalization,
        PrimaryBranding,
        ProgramTile,
        ProgramTile1,
        ProgramVerticalTile,
        ProgramVerticalTile1,
        Rating,
        Rights,
        SeriesArtwork,
        SeriesArtwork1,
        TitleTreatmentHorizontal,
        TitleTreatmentHorizontal1,
        UserState,
        VideoHorizontalHero,
        VideoHorizontalHero1,
        VideoHorizontalHero2,
        VodItems,
    )

__all__ = [
    "Accent",
    "Artwork",
    "Artwork1",
    "Artwork2",
    "Artwork3",
    "Availability",
    "BrandLogo",
    "BrandLogoBottomRight",
    "BrandLogoTopRight",
    "BrandWatermark",
    "BrandWatermarkBottomRight",
    "BrandWatermarkTopRight",
    "Browse",
    "Browse1",
    "Bundle",
    "DetailHorizontalHero",
    "DetailHorizontalHero1",
    "DetailVerticalHero",
    "DetailVerticalHero1",
    "Details",
    "Entity",
    "Entity1",
    "EpisodeModel",
    "ExternalIdentifier",
    "Focus",
    "MetricsInfo",
    "MetricsInfo1",
    "MetricsInfo2",
    "MetricsInfo3",
    "NetworkTile",
    "Personalization",
    "PrimaryBranding",
    "ProgramTile",
    "ProgramTile1",
    "ProgramVerticalTile",
    "ProgramVerticalTile1",
    "Rating",
    "Rights",
    "SeriesArtwork",
    "SeriesArtwork1",
    "TitleTreatmentHorizontal",
    "TitleTreatmentHorizontal1",
    "UserState",
    "VideoHorizontalHero",
    "VideoHorizontalHero1",
    "VideoHorizontalHero2",
    "VodItems",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> EpisodeModel:
    """Read a downloaded file into EpisodeModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
